spring:
  datasource:
    url: jdbc:mysql://your-mysql-domain/your-database?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false
    username: your-username
    password: your-password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
