server:
  port: 8902
  servlet:
    context-path: /client2

spring:
  application:
    name: client2service
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**

security:
  oauth2:
    client:
      client-id: client2
      client-secret: 123456
      user-authorization-uri: http://127.0.0.1:8900/sso/oauth/authorize
      access-token-uri: http://127.0.0.1:8900/sso/oauth/token
    resource:
      jwt:
        key-uri: http://127.0.0.1:8900/sso/oauth/token_key